### ISSUE TITLE
Publish vokomokum members docker image

### ISSUE THREAD

**Issue by wvengen** [vokomokum/vkmkm-erp#6]
In the Docker [vokomokum organisation](https://hub.docker.com/orgs/vokomokum), with auto-build from this repository, so that we can use it in [vkmk-deploy](https://github.com/vokomokum/vkmkm-deploy).

**Comment by nhoening** [comment]
To be clear, what you mean is to host https://hub.docker.com/repository/docker/nhoening/vokomokum-members not on my personal account, but on the vokomokum organisation, right?

**Comment by nhoening** [comment]
I published it in our organization, see [here](https://hub.docker.com/orgs/vokomokum/repositories). Hope that helps!

**Comment by wvengen** [comment]
Yes, thankyou!
Do we want to enable auto-builds, or would you rather do that manually (to avoid upgrade issues)?

**Comment by nhoening** [comment]
Auto-builds from github to Docker? I believe it makes sense to try, would love to learn. I guess there is a Github Action recipe?

Am 21. Oktober 2020 14:10:22 MESZ schrieb wvengen <notifications@github.com>:
>Yes, thankyou!
>Do we want to enable auto-builds, or would you rather do that manually
>(to avoid upgrade issues)?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/vokomokum/vkmkm-erp/issues/6#issuecomment-713523284

-- Gesendet von /e/ Mail.

**Comment by wvengen** [comment]
This can be setup in Docker Hub, which can also build a new container when the base image changes (which is a requirement for automated security updates from the base image - you won't get this so easily with Github Actions).

**Comment by nhoening** [comment]
Okay let's try that! That would be only for the :latest image right?

**Comment by wvengen** [comment]
I've enabled autobuild for the `latest` image indeed.
One can also trigger builds on tags that are tagged in Docker Hub as well (but we don't have releases here, yet).
